# site settings
title: Patrick McKenzie
subtitle: by HTML5 UP
email: p.mckenzie@columbia.edu
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: # the subpath of your site, e.g. /blog
url: patrickmckenzie.org # the base hostname & protocol for your site
author:
street_address: 
city: New York
state: NY
zip_code: 10027
country: United States of America
phone: (501) 941-0767

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.cpm/pmckenz1
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/patastic
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/PatrickMcKen_Z

# build settings
markdown: kramdown

sass:
  style: compressed
